weather-client:
    weather-url: https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&units=imperial&appid={apiKey}
    weather-zip-url: https://api.openweathermap.org/data/2.5/weather?zip={zip}&units=imperial&appid={apiKey}
    forecast-url: https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&units=imperial&appid={apiKey}
    client-api-key:
